version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: dms-postgres
    environment:
      POSTGRES_DB: document_management
      POSTGRES_USER: dms_user
      POSTGRES_PASSWORD: dms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dms_user -d document_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dms-network

  # Database admin tool (optional)
  adminer:
    image: adminer:latest
    container_name: dms-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - dms-network
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette
    profiles:
      - admin

volumes:
  postgres_data:
    driver: local

networks:
  dms-network:
    driver: bridge
