export const TOKENS = {
  // Repositories
  DOCUMENT_REPOSITORY: Symbol.for("DOCUMENT_REPOSITORY"),
  DOCUMENT_VERSION_REPOSITORY: Symbol.for("DOCUMENT_VERSION_REPOSITORY"),
  ACCESS_POLICY_REPOSITORY: Symbol.for("ACCESS_POLICY_REPOSITORY"),
  DOWNLOAD_TOKEN_REPOSITORY: Symbol.for("DOWNLOAD_TOKEN_REPOSITORY"),
  STORAGE_SERVICE: Symbol.for("STORAGE_SERVICE"),
  
  // Services
  ACCESS_CONTROL_SERVICE: Symbol.for("ACCESS_CONTROL_SERVICE"),
  AUDIT_LOGGER_SERVICE: Symbol.for("AUDIT_LOGGER_SERVICE"),
  
  // Workflows
  DOCUMENT_WORKFLOW: Symbol.for("DOCUMENT_WORKFLOW"),
  UPLOAD_WORKFLOW: Symbol.for("UPLOAD_WORKFLOW"),
  ACCESS_POLICY_WORKFLOW: Symbol.for("ACCESS_POLICY_WORKFLOW"),
  DOWNLOAD_TOKEN_WORKFLOW: Symbol.for("DOWNLOAD_TOKEN_WORKFLOW")
} as const;
